name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Upgrade pip and Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install --only dev

    - name: Update version in README
      run: poetry run python update_readme.py
      if: github.ref == 'refs/heads/main'

    - name: Run Black
      run: poetry run black --check .

    - name: Run MyPy
      run: poetry run mypy src --install-types --non-interactive

    - name: Run Flake8
      run: poetry run flake8 src

    - name: Run Pytest
      run: poetry run pytest

