name: UpdateReadme

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update_version:
    needs: [black, mypy, flake8, pytest]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --only dev
      - name: Update version in README
        run: poetry run python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README version" || echo "No changes to commit"
          git push